### ISSUE TITLE
<vaadin-dropdown-menu>

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-core#136]
The API should equal to our other "dropdown" elements:
```
<vaadin-dropdown-menu>
  <template>
    <vaadin-listbox>
      <vaadin-item>foo</vaadin-item>
      <vaadin-item>bar</vaadin-item>
      <vaadin-item>baz</vaadin-item>
    <vaadin-listbox>
  </template>
</vaadin-dropdown-menu>
```

- Should contain a read-only `<vaadin-text-field>`
- (Create `<vaadin-item>` repo (It's just a simple container at first))
- `<vaadin-dropdown-menu>` primarily accepts `vaadin-nav` -family selectors (iron-selector support can be added later)
- The overlay should cover the element
  - Consider pros/cons of re-using `<vaadin-context-menu>` as basis here

Remaining tasks:
- [x] Switch to fullscreen mode on narrow devices (like vaadin-context-menu does)
- [x] Retain overlay's relative position on scroll
  - When the overlay is opened, store it's relative position from the text-field and restore that offset on scroll (like vaadin-combo-box does)
- [x] slot=prefix should be available for the user
- [x] fix placeholder
- [ ] more unit tests
- [ ] visual tests
- [x] release alpha1
