### ISSUE TITLE
Collapsible panel (vaadin-details)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core#80]
_From @jouni on September 11, 2015 12:52_

A component to show more content when the user requests it, usually by clicking the panel header to reveal more content below it.

Polymer Elements has `iron-collapse` which we can utilize, but we could provide a more polished element, since currently it requires some boilerplate to trigger the opening and closing, and doesn’t provide lazy-loading content for instance, and doesn’t provide any default styles for material design.

Suggested element name: `vaadin-details` (since HTML actually has a draft spec for this element named `details`).
#### UI Design
- [x] End user feature design (what does it do, responsive behavior, etc.)
- [x] Graphical design
- [x] Prototype implementation for automatic scrolling behavior on small screen devices
- [ ] User testing for prototype
#### Technical design
- [ ] Technical feature design
- [ ] API design (element name, light dom api, etc.)
- [ ] Keyboard navigation and screen reader support
#### Attachments on Google Drive (private):
- [End user feature design](https://docs.google.com/document/d/1DBjYcUs9wMBGCne5VNIJ1fWev5pBQTk-iFVeDyd_eHk/edit)
- [Graphical designs](https://drive.google.com/drive/folders/0BzkWbWvgmkIxU1hCeE9mMUNsV2c)

_Copied from original issue: vaadin/vaadin-details#1_

**Comment by jouni** [comment]
HTML defines (or has a draft at least) for a `<details>` element, which is the same thing as this component (and WebKit and Blink implement that, Firefox doesn’t). We should perhaps try to follow that spec.

E.g.

```
<vaadin-details>
  <summary>Comments: <span>[[numOfComments]]</span></summary>
  <vaadin-details-content path="path/to/lazy-loaded-comments.html"></vaadin-details-content>
</vaadin-details>
```

or 

```
<vaadin-details>
  <summary>More info</summary>
  <p>Static content inside the disclosure.</p>
  <p>There could be multiple elements inside here, 
     and all of those would be considered as the "content", 
     apart from the `summary` element.
</vaadin-details>
```

**Comment by jouni** [comment]
Look at the [lazy-pages](http://robdodson.github.io/lazy-pages/bower_components/lazy-pages/) element as example of lazy-loading of the content

**Comment by jouni** [comment]
_From @tuomasnironen on September 14, 2015 11:4_

Prototyped UI with "Principle" tool (http://principleformac.com/). Does not offer exporting interactive prototype nor layout formatting as in original designs.
https://drive.google.com/open?id=0BzkWbWvgmkIxaGFuZk55ci1aUjg

**Comment by jouni** [comment]
That looks nice, at least as a side-viewer. So Principle doesn’t offer a way to let others try out that prototype interactively?

**Comment by jouni** [comment]
_From @tuomasnironen on September 15, 2015 5:19_

Nope, unless you have the Principle installed yourself for testing project files.

**Comment by jouni** [comment]
About lazy loading: the Polymer team is about to release an element regarding that exact functionality, so we should wait for that instead of implementing something similar ourselves at this moment.

**Comment by jouni** [comment]
For the record, the designs in the original description (from over 2 years ago) are no longer up to date, and can be discarded. Further design discussion/iteration will take place in specific issues in the [vaadin-accordion](https://github.com/vaadin/vaadin-accordion) repo.

**Comment by heruan** [comment]
What is the relation between `vaadin-details` and `vaadin-accordion`, and how they relate to `vaadin-grid` row details?

**Comment by web-padawan** [comment]
Going into a bit more detail, `vaadin-accordion-panel` is internally an extension of `vaadin-details` and leverage the same styling API and accessibility features.

**Comment by tomivirkki** [comment]
Releases
- Details
  - [Web Component](https://github.com/vaadin/vaadin-details/releases/tag/v1.0.0)
  - [Flow Component](https://github.com/vaadin/vaadin-details-flow/releases/tag/1.0.0.beta1)
- Accordion
  - [Web Component](https://github.com/vaadin/vaadin-accordion/releases/tag/v1.0.0)
  - [Flow Component](https://github.com/vaadin/vaadin-accordion-flow/releases/tag/1.0.0.beta2)
